# Generated by Django 5.2 on 2025-05-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_tracker', '0002_bank_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.CharField(choices=[], default='head_office', max_length=255),
            preserve_default=False,
        ),
    ]
