# Generated by Django 5.2 on 2025-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_tracker', '0004_alter_bankstatement_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bankstatementchangehistory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='branch',
            field=models.CharField(blank=True, choices=[('head_office', 'प्रधान कार्यलय'), ('chabahil', 'चाबहिल'), ('lagankhel', 'लगनखेल'), ('kalanki', 'कलंकी'), ('suryabinayak', 'सूर्यविनायक'), ('banepa', 'बनेपा'), ('biratnagar', 'विराटनगर'), ('birgunj', 'वीरगञ्ज'), ('pokhara', 'पोखरा'), ('butwal', 'बुटवल'), ('nepalgunj', 'नेपालगञ्ज'), ('dhangadhi', 'धनगढी'), ('hetauda', 'हेटौडा'), ('bhaktapur', 'भक्तपुर'), ('baglung', 'बागलुङ'), ('dhankuta', 'धनकुटा'), ('birtamod', 'बिर्तामोड'), ('narayangadh', 'नारायणगढ'), ('ghorahi', 'घोराही')], help_text='Receipt Issue From Branch', max_length=255, null=True),
        ),
    ]
