# Generated by Django 5.2 on 2025-11-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement_tracker', '0008_alter_bankstatement_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankstatement',
            options={'ordering': ['-created_date'], 'verbose_name': 'Bank Statement', 'verbose_name_plural': 'Bank Statements Reconciliation'},
        ),
    ]
