# Generated by Django 5.2 on 2025-11-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_tracker', '0009_alter_bankstatement_options'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Your Current Dept or Branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ticket.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_it_dept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(blank=True, choices=[('Assistant 4', 'Assistant 4'), ('Assistant 5', 'Assistant 5'), ('Assistant Manager ', 'Assistant Manager '), ('Deputy Manager', 'Deputy Manager'), ('Joint Manager', 'Joint Manager'), ('Manager', 'Manager'), ('Chief Manager', 'Chief Manager')], max_length=255, null=True),
        ),
    ]
