# Generated by Django 5.2 on 2025-11-20 11:55

import django.db.models.deletion
import rjbcl.common_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_tracker', '0010_user_department_user_is_global_user_is_it_dept_and_more'),
        ('ticket', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, default=rjbcl.common_data.get_default_department, help_text='Your Current Dept or Branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ticket.department'),
        ),
    ]
