# Generated by Django 5.2 on 2025-11-11 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('Core System', 'Core System'), ('CRM', 'CRM'), ('Payment Gateway', 'Payment Gateway'), ('Document Management', 'Document Management'), ('Analytics', 'Analytics'), ('Other', 'Other'), ('Toner Refill', 'Toner Refill'), ('Computer Maintenance', 'Computer Maintenance'), ('Electricity', 'Electricity'), ('Printer Maintenance', 'Printer Maintenance'), ('Network', 'Network'), ('Software', 'Software'), ('Hardware', 'Hardware')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category Type',
                'verbose_name_plural': 'Categories Types',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_branch', models.BooleanField(default=False)),
                ('sla_hours', models.IntegerField(default=48, help_text='SLA hours for this department')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Department and Branches',
                'verbose_name_plural': 'Departments and Branches',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('identifier', models.CharField(blank=True, help_text='PolicyNo, AgentCode, RoomNo, Your name', max_length=100, null=True)),
                ('ticket_priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('current_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending Customer', 'Pending Customer Response'), ('Pending Third Party', 'Pending Third Party'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Reopened', 'Reopened'), ('Transferred', 'Transferred to Another Department')], default='Open', max_length=50)),
                ('transfer_notes', models.TextField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('New Business', 'New Business'), ('Renewal', 'Renewal'), ('Loan I', 'Loan Against Policy Individual'), ('Loan G', 'Loan Against Policy Group'), ('Surrender I', 'Policy Surrender Individual'), ('Surrender G', 'Policy Surrender Group'), ('Maturity', 'Maturity Claim'), ('Reinsurance', 'Reinsurance'), ('Actuary', 'Actuary'), ('Individual Death Claim', 'Death Claim Individual'), ('Group Death Claim', 'Death Claim Group'), ('Nomination Change Group', 'Nomination Change Group'), ('Nomination Change Individual', 'Nomination Change Individual'), ('Address Change', 'Address Change'), ('Premium Payment', 'Premium Payment Issue'), ('Policy Revival', 'Policy Revival'), ('Software Change Request', 'Software Change Request'), ('General', 'General')], max_length=50)),
                ('issue_type', models.CharField(blank=True, choices=[('Bug Fix', 'Bug and Error Fix'), ('Enhancement', 'Enhancement'), ('New Feature', 'New Feature'), ('Integration', 'Integration'), ('Security', 'Security Update'), ('Maintenance', 'Maintenance'), ('Configuration', 'Configuration')], max_length=50, null=True)),
                ('urgency_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True)),
                ('estimated_effort_hours', models.IntegerField(blank=True, null=True)),
                ('business_impact', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('sla_due_date', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('memo_required', models.BooleanField(default=False)),
                ('memo', models.FileField(blank=True, null=True, upload_to='ticket_memos/')),
                ('is_final', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_tickets', to='ticket.department')),
                ('originating_department', models.ForeignKey(blank=True, help_text='Department where ticket was originally created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_originated_tickets', to='ticket.department')),
                ('to_department', models.ForeignKey(blank=True, help_text='Department where ticket will be sent', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_to_department_transfer', to='ticket.department')),
                ('transferred_from', models.ForeignKey(blank=True, help_text='Department from which ticket was transferred', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_transferred_tickets', to='ticket.department')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_outgoing_transfers', to='ticket.department')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_incoming_transfers', to='ticket.department')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Department Transfer',
                'verbose_name_plural': 'Department Transfers',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_step', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='Pending', max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Change Request Workflow',
                'verbose_name_plural': 'Change Request Workflows',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketDiscussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System Message'), ('resolution', 'Resolution Note'), ('transfer', 'Department Transfer')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket.ticketdiscussion')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Discussion',
                'verbose_name_plural': 'Ticket Discussions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status History',
                'ordering': ['-changed_at'],
            },
        ),
    ]
