# Generated by Django 5.2 on 2025-11-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_category_category_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
