# Generated by Django 5.2 on 2025-11-20 12:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(help_text='Govt Code/Barcode (e.g., MOF-IT-001)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Asset Name')),
                ('category', models.CharField(choices=[('HW', 'Hardware (Physical)'), ('SW', 'Software (Installed/SaaS)'), ('LIC', 'License / Subscription'), ('NET', 'Network Infrastructure'), ('AMC', 'AMC / Service Contract')], max_length=5)),
                ('status', models.CharField(choices=[('PLAN', 'Planning/Procurement'), ('ACTIVE', 'Operational (Active)'), ('MAINT', 'In Maintenance/Repair'), ('RETIRED', 'Retired/Disposed'), ('LOST', 'Lost/Stolen')], default='ACTIVE', max_length=10)),
                ('fiscal_year', models.CharField(choices=[('2081/82', '2081/82 B.S.'), ('2082/83', '2082/83 B.S.'), ('2083/84', '2083/84 B.S.')], help_text='e.g., 2080/81', max_length=10, verbose_name='Fiscal Year (A.B.)')),
                ('procurement_method', models.CharField(choices=[('DIRECT', 'Direct Purchase (Sojhai Kharid)'), ('SEALED', 'Sealed Quotation (Darbhau Patra)'), ('TENDER', 'Open Tender (Bolpatra)'), ('DONATION', 'Grant/Donation')], default='DIRECT', max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Kharid Miti')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cost (NPR)')),
                ('vendor_name', models.CharField(blank=True, help_text='Supplier/Vendor', max_length=200)),
                ('invoice_no', models.CharField(blank=True, max_length=100, verbose_name='Bill/Invoice No')),
                ('confidentiality', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text='Impact if data is disclosed')),
                ('integrity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text='Impact if data is corrupted')),
                ('availability', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, help_text='Impact if system goes down')),
                ('risk_score', models.IntegerField(default=0, editable=False)),
                ('criticality', models.CharField(default='Low', editable=False, max_length=10)),
                ('amc_expiry_date', models.DateField(blank=True, help_text='System will alert 30 days before this date', null=True, verbose_name='License/AMC Expiry')),
                ('department', models.CharField(max_length=100, verbose_name='Sakha/Department')),
                ('custodian', models.CharField(help_text='Staff Name', max_length=100, verbose_name='Responsible Person')),
                ('location', models.CharField(help_text='Room No / Branch', max_length=100)),
                ('specs', tinymce.models.HTMLField(blank=True, help_text='RAM, Storage, IP Address, etc.')),
            ],
        ),
    ]
