# Generated by Django 4.2.26 on 2025-11-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0002_itasset_ip_address_alter_itasset_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='it_assets_document/'),
        ),
    ]
