# Generated by Django 5.2 on 2025-11-20 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='e.g., 21/10/2022-L/097/44', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('income_source', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 9 to 10-digit Nepali number (e.g., +97798XXXXXXXX or 98XXXXXXXX).', regex='^(?:\\+977|0)?\\d{9,10}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Optional. E.g., user@example.com', max_length=254)),
                ('province', models.CharField(choices=[('Koshi', 'Koshi'), ('Madhesh', 'Madhesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('local_unit', models.CharField(max_length=100, verbose_name='Local Unit (VDC/Municipality)')),
                ('address', models.CharField(max_length=255, verbose_name='Ward/Tole')),
                ('temporary_address', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('grandfather_name', models.CharField(blank=True, max_length=200)),
                ('spouse_name', models.CharField(blank=True, help_text='Enter if married', max_length=200)),
                ('is_insured', models.BooleanField(default=False, verbose_name='Is Confirmed Insured?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
