# Generated by Django 5.2 on 2025-11-11 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('parent_menu', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ISolution Menu / Module',
                'verbose_name_plural': 'Isolution Menus / Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='RJBCL office email')),
                ('phone_no', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(choices=[('Nepali', 'Nepali'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=30)),
                ('document_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Voter ID', 'Voter ID')], default='Citizen', max_length=50)),
                ('citizen_no', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, choices=[('Koshi', 'Koshi Province'), ('Madhesh Province', 'Madhesh Province'), ('Bagmati Province', 'Bagmati Province'), ('Gandaki Province', 'Gandaki Province'), ('Lumbini Province', 'Lumbini Province'), ('Karnali Province', 'Karnali Province'), ('Sudurpashchim Province', 'Sudurpashchim Province')], max_length=50, null=True)),
                ('designation', models.CharField(choices=[('Assistant 4', 'Assistant 4'), ('Assistant 5', 'Assistant 5'), ('Assistant Manager ', 'Assistant Manager '), ('Deputy Manager', 'Deputy Manager'), ('Joint Manager', 'Joint Manager'), ('Manager', 'Manager'), ('Chief Manager', 'Chief Manager')], max_length=100)),
                ('allow_approve_transaction', models.BooleanField(default=False)),
                ('allow_back_date', models.BooleanField(default=False)),
                ('is_regional_head', models.BooleanField(default=False)),
                ('is_branch_manager', models.BooleanField(default=False)),
                ('allow_advance_payment', models.BooleanField(default=False)),
                ('is_me_user', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Personal Email')),
                ('request_type', models.CharField(choices=[('New Access', 'New Access'), ('Modification', 'Access Modification'), ('Deactivation', 'Deactivation')], default='New Access', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('memo_reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('memo_date', models.DateField(blank=True, null=True)),
                ('memo_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_form', models.FileField(blank=True, null=True, upload_to='')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_approved', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='New user Department or branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.department')),
                ('permissions_requested', models.ManyToManyField(related_name='user_requests', to='user_request_app.menuitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Request',
                'verbose_name_plural': 'Request -> New Isolution User',
                'ordering': ['-request_date'],
            },
        ),
    ]
