# Generated by Django 5.2 on 2025-11-05 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('parent_menu', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Menu / Module',
                'verbose_name_plural': 'Menus / Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('department', models.CharField(choices=[('Administration', 'Administration'), ('Individual Underwriting', 'Individual Underwriting'), ('Group Underwriting', 'Group Underwriting'), ('Claim', 'Claim'), ('Policy Loan', 'Policy Loan'), ('Agent Commission', 'Agent Commission'), ('Reinsurance', 'Reinsurance'), ('Finance', 'Finance'), ('Account', 'Account'), ('Actuary', 'Actuary'), ('Agency Renewal', 'Agency Renewal'), ('Agency Loan', 'Agency Loan'), ('Executive', 'Executive'), ('General Service', 'General Service'), ('Store', 'Store'), ('Foreign', 'Foreign'), ('Policy Service', 'Policy Service'), ('Information Technology', 'Information Technology'), ('Claim Payment', 'Claim Payment'), ('Marketing', 'Marketing'), ('Investment', 'Investment')], default='Administration', max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(choices=[('Nepali', 'Nepali'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=30)),
                ('document_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Voter ID', 'Voter ID')], default='Citizen', max_length=50)),
                ('citizen_no', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, choices=[('Koshi', 'Koshi Province'), ('Madhesh Province', 'Madhesh Province'), ('Bagmati Province', 'Bagmati Province'), ('Gandaki Province', 'Gandaki Province'), ('Lumbini Province', 'Lumbini Province'), ('Karnali Province', 'Karnali Province'), ('Sudurpashchim Province', 'Sudurpashchim Province')], max_length=50, null=True)),
                ('designation', models.CharField(choices=[('Assistant', 'Assistant'), ('Officer', 'Officer'), ('Senior Officer', 'Senior Officer'), ('Manager', 'Manager'), ('Senior Manager', 'Senior Manager'), ('Deputy General Manager', 'Deputy General Manager'), ('General Manager', 'General Manager')], max_length=100)),
                ('allow_approve_transaction', models.BooleanField(default=False)),
                ('allow_back_date', models.BooleanField(default=False)),
                ('is_regional_head', models.BooleanField(default=False)),
                ('is_branch_manager', models.BooleanField(default=False)),
                ('allow_advance_payment', models.BooleanField(default=False)),
                ('is_me_user', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('New Access', 'New Access'), ('Modification', 'Access Modification'), ('Deactivation', 'Deactivation')], default='New Access', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('memo_reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('memo_date', models.DateField(blank=True, null=True)),
                ('memo_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_form', models.FileField(upload_to='')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_approved', to=settings.AUTH_USER_MODEL)),
                ('permissions_requested', models.ManyToManyField(related_name='user_requests', to='user_request_app.menuitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Request',
                'verbose_name_plural': 'User Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
