# Generated by Django 5.2 on 2025-11-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='approval_form',
            field=models.FileField(blank=True, null=True, upload_to='isolution/user_request', verbose_name='फारम सबमिट गरेपछि  डाउनलोड गरी हस्ताक्षर गरेर फेरि स्क्यान गरी पुनः यहाँ अपलोड गर्नुहोस्'),
        ),
    ]
