# Generated by Django 5.2 on 2025-11-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name'], 'verbose_name': 'ISolution Menu / Module', 'verbose_name_plural': 'Isolution Menus / Modules'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'User Request', 'verbose_name_plural': 'Request -> New Isolution User'},
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='branch',
            field=models.CharField(choices=[('head_office', 'प्रधान कार्यलय'), ('chabahil', 'चाबहिल'), ('lagankhel', 'लगनखेल'), ('kalanki', 'कलंकी'), ('suryabinayak', 'सूर्यविनायक'), ('banepa', 'बनेपा'), ('biratnagar', 'विराटनगर'), ('birgunj', 'वीरगञ्ज'), ('pokhara', 'पोखरा'), ('butwal', 'बुटवल'), ('nepalgunj', 'नेपालगञ्ज'), ('dhangadhi', 'धनगढी'), ('hetauda', 'हेटौडा'), ('bhaktapur', 'भक्तपुर'), ('baglung', 'बागलुङ'), ('dhankuta', 'धनकुटा'), ('birtamod', 'बिर्तामोड'), ('narayangadh', 'नारायणगढ'), ('ghorahi', 'घोराही'), ('janakpur', 'जनकपुर'), ('surkhet', 'सुर्खेत'), ('ithari', 'इटहरी'), ('mahendranagar', 'महेन्द्रनगर')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='designation',
            field=models.CharField(choices=[('Assistant 4', 'Assistant 4'), ('Assistant 5', 'Assistant 5'), ('Assistant Manager ', 'Assistant Manager '), ('Deputy Manager', 'Deputy Manager'), ('Joint Manager', 'Joint Manager'), ('Manager', 'Manager'), ('Chief Manager', 'Chief Manager')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='RJBCL office email'),
        ),
    ]
