# Generated by Django 5.2 on 2025-11-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_options'),
        ('user_request_app', '0002_alter_userrequest_approval_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('designation', models.CharField(choices=[('Assistant 4', 'Assistant 4'), ('Assistant 5', 'Assistant 5'), ('Assistant Manager ', 'Assistant Manager '), ('Deputy Manager', 'Deputy Manager'), ('Joint Manager', 'Joint Manager'), ('Manager', 'Manager'), ('Chief Manager', 'Chief Manager')], max_length=255)),
                ('system_type', models.CharField(choices=[('ACTIVE_DIRECTORY', 'Active Directory'), ('EMAIL', 'Email Account'), ('HR_SYSTEM', 'HR System'), ('OTHER', 'Other')], default='ACTIVE_DIRECTORY', max_length=20, verbose_name='System Type')),
                ('approval_form', models.FileField(help_text='Upload scanned approval document', upload_to='approval_forms/', verbose_name='Approval Form')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('requested_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.department', verbose_name='Requesting Department')),
            ],
            options={
                'verbose_name': 'User Access Request',
                'verbose_name_plural': 'User Access Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
