# Generated by Django 5.2 on 2025-11-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_app', '0003_useraccessrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccessrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Computer, AD, Email -> User Access Request', 'verbose_name_plural': 'User Access Requests'},
        ),
        migrations.AlterField(
            model_name='useraccessrequest',
            name='approval_form',
            field=models.FileField(blank=True, help_text='Upload scanned approval document', null=True, upload_to='approval_forms/', verbose_name='Approval Form'),
        ),
    ]
