# Generated by Django 4.2.26 on 2025-11-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_app', '0004_alter_useraccessrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccessrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Computer, AD, Email -> User Access Request', 'verbose_name_plural': 'Computer, AD, Email -> User Access Request'},
        ),
    ]
