# Generated by Django 5.2 on 2025-11-20 13:32

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0003_alter_ticket_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='अनुरोध नं (Request Number)')),
                ('title', models.CharField(max_length=255, verbose_name='शीर्षक (Title)')),
                ('description', tinymce.models.HTMLField(help_text='समस्या वा आवश्यकताको पूर्ण विवरण', verbose_name='विस्तृत विवरण (Detailed Description)')),
                ('change_type', models.CharField(choices=[('STANDARD', 'मानक परिवर्तन (Standard Change)'), ('NORMAL', 'सामान्य परिवर्तन (Normal Change)'), ('EMERGENCY', 'आपतकालीन परिवर्तन (Emergency Change)')], default='NORMAL', max_length=20, verbose_name='परिवर्तनको प्रकार (Change Type)')),
                ('category', models.CharField(blank=True, choices=[('DATA_REQUEST', 'तथ्याङ्क माग (Data Request)'), ('DATA_MODIFICATION', 'तथ्याङ्क परिमार्जन (Data Modification)'), ('SYSTEM_ACCESS', 'प्रणाली पहुँच (System Access)'), ('NEW_FEATURE', 'नयाँ विशेषता (New Feature)'), ('BUG_FIX', 'समस्या समाधान (Bug Fix)'), ('CONFIGURATION', 'कन्फिगरेसन परिवर्तन (Configuration Change)'), ('HARDWARE', 'हार्डवेयर अनुरोध (Hardware Request)'), ('SOFTWARE', 'सफ्टवेयर स्थापना (Software Installation)'), ('TRAINING', 'तालिम अनुरोध (Training Request)'), ('REPORT', 'रिपोर्ट अनुरोध (Report Request)'), ('POLICY', 'नीति परिवर्तन (Policy Change)'), ('TONER_REFILL', 'टोनर रिफिल / प्रिन्टर सामग्री (Toner / Printer Consumables)'), ('PRINTER_ISSUE', 'प्रिन्टर / स्क्यानर समस्या (Printer/Scanner Issue)'), ('ID_CARD', 'कर्मचारी ID Card / Access Card Request'), ('ATTENDANCE', 'हाजिरी/बायोमेट्रिक समस्या (Attendance/Biometric Issue)'), ('INTERNET_WIFI', 'इन्टरनेट / WiFi समस्या (Internet/WiFi Issue)'), ('EMAIL_SUPPORT', 'ईमेल समर्थन (Email Support)'), ('MEETING_SUPPORT', 'मिटिङ / Zoom / Projector Support'), ('CCTV', 'CCTV Footage / Camera Issue'), ('BACKUP_RESTORE', 'ब्याकअप पुनःप्राप्ति (Backup Restore Request)'), ('VENDOR_COORD', 'Vendor Coordination Request'), ('OFFICE_SHIFT', 'अफिस सार्ने / PC Movement (Office Shifting Support)'), ('WORKFLOW_ISSUE', 'Workflow / Approval समस्या'), ('DIGITAL_SIGNATURE', 'डिजिटल Signature / Token Issue'), ('ERP_SUPPORT', 'ERP/Core Insurance Support (Non-Change Issues)'), ('OTHER', 'अन्य (Other)')], max_length=30, null=True, verbose_name='श्रेणी (Category)')),
                ('priority', models.CharField(choices=[('LOW', 'न्यून (Low)'), ('MEDIUM', 'मध्यम (Medium)'), ('HIGH', 'उच्च (High)'), ('CRITICAL', 'अत्यन्त जरुरी (Critical)')], default='MEDIUM', max_length=10, verbose_name='प्राथमिकता (Priority)')),
                ('business_justification', models.TextField(blank=True, help_text='यो परिवर्तन किन आवश्यक छ?', null=True, verbose_name='व्यावसायिक औचित्य (Business Justification)')),
                ('impact_assessment', models.CharField(choices=[('LOW', 'न्यून प्रभाव (Low Impact)'), ('MEDIUM', 'मध्यम प्रभाव (Medium Impact)'), ('HIGH', 'उच्च प्रभाव (High Impact)'), ('CRITICAL', 'गम्भीर प्रभाव (Critical Impact)')], default='MEDIUM', max_length=10, verbose_name='प्रभाव मूल्यांकन (Impact Assessment)')),
                ('risk_level', models.CharField(choices=[('LOW', 'न्यून जोखिम (Low Risk)'), ('MEDIUM', 'मध्यम जोखिम (Medium Risk)'), ('HIGH', 'उच्च जोखिम (High Risk)'), ('VERY_HIGH', 'अति उच्च जोखिम (Very High Risk)')], default='MEDIUM', max_length=10, verbose_name='जोखिम स्तर (Risk Level)')),
                ('affected_systems', models.TextField(blank=True, help_text='कुन प्रणाली वा मोड्युलहरू प्रभावित हुन्छन्?', verbose_name='प्रभावित प्रणालीहरू (Affected Systems)')),
                ('rollback_plan', tinymce.models.HTMLField(blank=True, help_text='समस्या भएमा पहिलेको अवस्थामा फर्कने योजना', verbose_name='फिर्ता योजना (Rollback Plan)')),
                ('reference_number', models.CharField(blank=True, help_text='Policy/Claim/Contract Number आदि', max_length=100, verbose_name='सन्दर्भ नं (Reference Number)')),
                ('current_value', models.TextField(blank=True, verbose_name='हालको विवरण (Current Value)')),
                ('proposed_value', models.TextField(blank=True, verbose_name='प्रस्तावित विवरण (Proposed Value)')),
                ('data_privacy_confirmed', models.BooleanField(default=False, help_text='म तथ्याङ्कको गोपनीयता कायम राख्ने घोषणा गर्दछु', verbose_name='गोपनीयता पुष्टि (Data Privacy Confirmed)')),
                ('regulatory_compliance_check', models.BooleanField(default=False, help_text='NRB/Regulatory requirements पूरा भएको छ?', verbose_name='नियामक अनुपालन (Regulatory Compliance)')),
                ('status', models.CharField(choices=[('DRAFT', 'मस्यौदा (Draft)'), ('SUBMITTED', 'पेश गरिएको (Submitted)'), ('UNDER_REVIEW', 'समीक्षाधीन (Under Review)'), ('APPROVED', 'स्वीकृत (Approved)'), ('REJECTED', 'अस्वीकृत (Rejected)'), ('IN_PROGRESS', 'कार्यान्वयनमा (In Progress)'), ('PENDING_INFO', 'जानकारी बाँकी (Pending Information)'), ('ON_HOLD', 'रोकिएको (On Hold)'), ('COMPLETED', 'सम्पन्न (Completed)'), ('CLOSED', 'बन्द गरिएको (Closed)'), ('CANCELLED', 'रद्द गरिएको (Cancelled)')], default='DRAFT', max_length=20, verbose_name='अवस्था (Status)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='सिर्जना मिति (Created At)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='पेश गरेको मिति (Submitted At)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='समीक्षा मिति (Reviewed At)')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='स्वीकृति मिति (Approved At)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='सुरु मिति (Started At)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='सम्पन्न मिति (Completed At)')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='बन्द गरेको मिति (Closed At)')),
                ('expected_completion_date', models.DateField(blank=True, null=True, verbose_name='अपेक्षित पूर्णता मिति (Expected Completion)')),
                ('response_notes', models.TextField(blank=True, help_text='विभागको प्रतिक्रिया वा टिप्पणी', verbose_name='प्रतिक्रिया टिप्पणी (Response Notes)')),
                ('resolution_details', models.TextField(blank=True, help_text='अनुरोध कसरी पूरा गरियो', verbose_name='समाधान विवरण (Resolution Details)')),
                ('closure_notes', models.TextField(blank=True, verbose_name='बन्द गर्ने टिप्पणी (Closure Notes)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='change_requests/%Y/%m/', verbose_name='संलग्नक (Attachment)')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='अन्तिम परिमार्जन (Last Modified)')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='स्वीकृतकर्ता (Approved By)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='जिम्मेवार व्यक्ति (Assigned To)')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_requests', to=settings.AUTH_USER_MODEL, verbose_name='पूर्णकर्ता (Completed By)')),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_requests', to='ticket.department', verbose_name='अनुरोध गर्ने विभाग (From Department)')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL, verbose_name='अनुरोधकर्ता (Requested By)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='समीक्षक (Reviewed By)')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_requests', to='ticket.department', verbose_name='अनुरोध प्राप्त गर्ने विभाग (To Department)')),
            ],
            options={
                'verbose_name': 'परिवर्तन अनुरोध (Change Request)',
                'verbose_name_plural': 'परिवर्तन अनुरोधहरू (Change Requests)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='request_attachments/%Y/%m/', verbose_name='फाइल (File)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='विवरण (Description)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='अपलोड मिति (Uploaded At)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rjbcl_workflow_manager.changerequest', verbose_name='अनुरोध (Request)')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='अपलोड गर्ने (Uploaded By)')),
            ],
            options={
                'verbose_name': 'संलग्नक (Attachment)',
                'verbose_name_plural': 'संलग्नकहरू (Attachments)',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='टिप्पणी (Comment)')),
                ('is_internal', models.BooleanField(default=False, help_text='केवल विभागीय कर्मचारीलाई देखिने', verbose_name='आन्तरिक टिप्पणी (Internal Comment)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='सिर्जना मिति (Created At)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rjbcl_workflow_manager.changerequest', verbose_name='अनुरोध (Request)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='प्रयोगकर्ता (User)')),
            ],
            options={
                'verbose_name': 'टिप्पणी (Comment)',
                'verbose_name_plural': 'टिप्पणीहरू (Comments)',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'सिर्जना गरियो (Created)'), ('SUBMITTED', 'पेश गरियो (Submitted)'), ('ASSIGNED', 'जिम्मेवारी दियो (Assigned)'), ('STATUS_CHANGED', 'अवस्था परिवर्तन (Status Changed)'), ('UPDATED', 'अद्यावधिक गरियो (Updated)'), ('COMMENTED', 'टिप्पणी थपियो (Commented)'), ('APPROVED', 'स्वीकृत गरियो (Approved)'), ('REJECTED', 'अस्वीकृत गरियो (Rejected)'), ('COMPLETED', 'सम्पन्न गरियो (Completed)'), ('CLOSED', 'बन्द गरियो (Closed)'), ('REOPENED', 'पुन: खोलियो (Reopened)')], max_length=20, verbose_name='कार्य (Action)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='समय (Timestamp)')),
                ('old_value', models.TextField(blank=True, verbose_name='पुरानो मूल्य (Old Value)')),
                ('new_value', models.TextField(blank=True, verbose_name='नयाँ मूल्य (New Value)')),
                ('field_changed', models.CharField(blank=True, max_length=100, verbose_name='परिवर्तन क्षेत्र (Field Changed)')),
                ('notes', models.TextField(blank=True, verbose_name='टिप्पणी (Notes)')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='गर्ने व्यक्ति (Performed By)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rjbcl_workflow_manager.changerequest', verbose_name='अनुरोध (Request)')),
            ],
            options={
                'verbose_name': 'अनुरोध इतिहास (Request History)',
                'verbose_name_plural': 'अनुरोध इतिहासहरू (Request Histories)',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status', 'priority'], name='rjbcl_workf_status_919a98_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['from_department', 'to_department'], name='rjbcl_workf_from_de_baa4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['request_number'], name='rjbcl_workf_request_ed6258_idx'),
        ),
    ]
