# Generated by Django 4.2.26 on 2025-11-24 05:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_options'),
        ('rjbcl_workflow_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Register Change Request)', 'verbose_name_plural': '1. Register Issue (अनुरोध गर्नुहोस)'},
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='category',
            field=models.CharField(blank=True, choices=[('DATA_REQUEST', 'तथ्याङ्क माग (Data Request)'), ('DATA_MODIFICATION', 'तथ्याङ्क परिमार्जन (Data Modification)'), ('SYSTEM_ACCESS', 'प्रणाली पहुँच (System Access)'), ('NEW_FEATURE', 'नयाँ विशेषता (New Feature)'), ('BUG_FIX', 'समस्या समाधान (Bug Fix)'), ('CONFIGURATION', 'कन्फिगरेसन परिवर्तन (Configuration Change)'), ('HARDWARE', 'हार्डवेयर अनुरोध (Hardware Request)'), ('SOFTWARE', 'सफ्टवेयर स्थापना (Software Installation)'), ('TRAINING', 'तालिम अनुरोध (Training Request)'), ('REPORT', 'रिपोर्ट अनुरोध (Report Request)'), ('POLICY', 'नीति परिवर्तन (Policy Change)'), ('TONER_REFILL', 'टोनर रिफिल / प्रिन्टर सामग्री (Toner / Printer Consumables)'), ('PRINTER_ISSUE', 'प्रिन्टर / स्क्यानर समस्या (Printer/Scanner Issue)'), ('ID_CARD', 'कर्मचारी ID Card / Access Card Request'), ('ATTENDANCE', 'हाजिरी/बायोमेट्रिक समस्या (Attendance/Biometric Issue)'), ('INTERNET_WIFI', 'इन्टरनेट / WiFi समस्या (Internet/WiFi Issue)'), ('EMAIL_SUPPORT', 'ईमेल समर्थन (Email Support)'), ('MEETING_SUPPORT', 'मिटिङ / Zoom / Projector Support'), ('CCTV', 'CCTV Footage / Camera Issue'), ('BACKUP_RESTORE', 'ब्याकअप पुनःप्राप्ति (Backup Restore Request)'), ('VENDOR_COORD', 'Vendor Coordination Request'), ('OFFICE_SHIFT', 'अफिस सार्ने / PC Movement (Office Shifting Support)'), ('WORKFLOW_ISSUE', 'Workflow / Approval समस्या'), ('DIGITAL_SIGNATURE', 'डिजिटल Signature / Token Issue'), ('ERP_SUPPORT', 'ERP/Core Insurance Support (Non-Change Issues)'), ('OTHER', 'अन्य (Other)')], max_length=30, null=True, verbose_name='श्रेणी '),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='change_type',
            field=models.CharField(choices=[('STANDARD', 'मानक परिवर्तन (Standard Change)'), ('NORMAL', 'सामान्य परिवर्तन (Normal Change)'), ('EMERGENCY', 'आपतकालीन परिवर्तन (Emergency Change)')], default='NORMAL', max_length=20, verbose_name='परिवर्तनको प्रकार'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='description',
            field=tinymce.models.HTMLField(help_text='समस्या वा आवश्यकताको पूर्ण विवरण', verbose_name='विस्तृत विवरण'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='from_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_requests', to='ticket.department', verbose_name='अनुरोध गर्ने विभाग '),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Policy/Claim/Contract Number/RoomNo/Your location आदि', max_length=100, verbose_name='सन्दर्भ नं'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='शीर्षक'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='to_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_requests', to='ticket.department', verbose_name='अनुरोध प्राप्त गर्ने विभाग'),
        ),
    ]
