# Generated by Django 4.2.26 on 2025-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjbcl_workflow_manager', '0002_alter_changerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='category',
            field=models.CharField(blank=True, choices=[('UNDERWRITING_ISSUE', 'बीमालेखन समस्या (Underwriting Issue)'), ('CLAIM_PROCESSING_ISSUE', 'दाबी प्रसोधन समस्या (Claim Processing Issue)'), ('PREMIUM_ACCOUNTING_ISSUE', 'प्रिमियम / लेखा समस्या (Premium & Accounting Issue)'), ('POLICY_SERVICE_ISSUE', 'पोलिसी सेवा समस्या (Policy Servicing Issue)'), ('AGENT_PORTAL_ISSUE', 'अभिकर्ता पोर्टल / आयोग समस्या (Agent Portal / Commission Issue)'), ('NETWORK_ISSUE', 'नेटवर्क / इन्टरनेट समस्या (Network/Internet Issue)'), ('PRINTER_ISSUE', 'प्रिन्टर / स्क्यानर समस्या (Printer/Scanner Issue)'), ('GENERAL_OFFICE_ISSUE', 'सामान्य अफिस समस्या (General Office Issue)')], max_length=30, null=True, verbose_name='श्रेणी '),
        ),
    ]
