# Generated by Django 5.2 on 2025-11-20 11:55

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0003_alter_ticket_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_type', models.CharField(choices=[('OUT', 'विभागबाट जारी (Outgoing/Given by Department)'), ('CEO', 'सीईओबाट स्वीकृत (CEO Approved/Received by Department)')], default='OUT', max_length=3, verbose_name='मेमोको प्रकार (Memo Type)')),
                ('fy_title', models.CharField(choices=[('2081/82', '2081/82 B.S.'), ('2082/83', '2082/83 B.S.'), ('2083/84', '2083/84 B.S.')], max_length=10, verbose_name='आ.व. (Fiscal Year)')),
                ('date_of_record', models.DateField(default=django.utils.timezone.now, verbose_name='मिति (Date of Issue/Approval)')),
                ('title', models.CharField(max_length=255, verbose_name='विषय (Title/Subject)')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='छोटो विवरण (Short Description)')),
                ('memo_document', models.FileField(upload_to='memos/%Y/%m/', verbose_name='मेमोको फाइल (Memo Document File)')),
                ('is_final', models.BooleanField(default=False, verbose_name='अन्तिम (Finalized/Locked)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos_created', to=settings.AUTH_USER_MODEL, verbose_name='सिर्जना गर्ने (Created By)')),
                ('created_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos_created_by', to='ticket.department', verbose_name='सिर्जना गर्ने विभाग (Creating Department)')),
                ('related_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos_related_to', to='ticket.department', verbose_name='सम्बन्धित विभाग (Related/Recipient Department)')),
            ],
            options={
                'verbose_name': 'मेमो रेकर्ड',
                'verbose_name_plural': 'मेमो रेकर्डहरू',
                'ordering': ['-date_of_record', 'fy_title'],
            },
        ),
    ]
