# Generated by Django 5.2 on 2025-11-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecord',
            name='memo_document',
            field=models.FileField(blank=True, null=True, upload_to='memos/%Y/%m/', verbose_name='मेमोको फाइल (Memo Document File)'),
        ),
    ]
