# Generated by Django 5.2 on 2025-11-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0002_alter_memorecord_memo_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecord',
            name='memo_type',
            field=models.CharField(choices=[('OUT', 'विभागबाट जारी (Outgoing/Given by Department)'), ('CEO', 'सीईओबाट स्वीकृत (CEO Approved/Received by Department)')], default='CEO', max_length=3, verbose_name='मेमोको प्रकार (Memo Type)'),
        ),
    ]
