# Generated by Django 4.2.26 on 2025-11-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0003_alter_memorecord_memo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecord',
            name='fy_title',
            field=models.CharField(choices=[('2078/79', '2078/79 B.S.'), ('2079/80', '2079/80 B.S.'), ('2080/81', '2080/81 B.S.'), ('2081/82', '2081/82 B.S.'), ('2082/83', '2082/83 B.S.'), ('2083/84', '2083/84 B.S.'), ('2084/85', '2085/85 B.S.')], max_length=10, verbose_name='आ.व. (Fiscal Year)'),
        ),
    ]
