# Generated by Django 5.2 on 2025-11-20 09:38

import rjbcl.common_data
import rjbcl.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=rjbcl.common_data.default_deadline, help_text='Time to complete the task'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Task Description', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, help_text='Task Details document pdf or word max 5 MB', null=True, upload_to='task_manager/document', validators=[rjbcl.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Task title or To Do title', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskdiscussion',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
